using Ardalis.SmartEnum;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;

namespace Maurosoft.Blazor.Tailwind.Core.Css;

/// <summary>
/// Utilities for controlling the BackgroundColor of an element.
/// For info, see <see href="https://tailwindcss.com/docs/background-color">background-color</see>
/// </summary>
public sealed class BackgroundColor : TailwindCssClassBase
{
    public static readonly BackgroundColor NotSet = new("notset", 1);
    public static readonly BackgroundColor Inherit = new("bg-inherit", 2);
    public static readonly BackgroundColor Current = new("bg-current", 3);
    public static readonly BackgroundColor Transparent = new("bg-transparent", 4);
    public static readonly BackgroundColor Black = new("bg-black", 5);
    public static readonly BackgroundColor White = new("bg-white", 6);
    public static readonly BackgroundColor Slate_50 = new("bg-slate-50", 7);
    public static readonly BackgroundColor Slate_100 = new("bg-slate-100", 8);
    public static readonly BackgroundColor Slate_200 = new("bg-slate-200", 9);
    public static readonly BackgroundColor Slate_300 = new("bg-slate-300", 10);
    public static readonly BackgroundColor Slate_400 = new("bg-slate-400", 11);
    public static readonly BackgroundColor Slate_500 = new("bg-slate-500", 12);
    public static readonly BackgroundColor Slate_600 = new("bg-slate-600", 13);
    public static readonly BackgroundColor Slate_700 = new("bg-slate-700", 14);
    public static readonly BackgroundColor Slate_800 = new("bg-slate-800", 15);
    public static readonly BackgroundColor Slate_900 = new("bg-slate-900", 16);
    public static readonly BackgroundColor Slate_950 = new("bg-slate-950", 17);
    public static readonly BackgroundColor Gray_50 = new("bg-gray-50", 18);
    public static readonly BackgroundColor Gray_100 = new("bg-gray-100", 19);
    public static readonly BackgroundColor Gray_200 = new("bg-gray-200", 20);
    public static readonly BackgroundColor Gray_300 = new("bg-gray-300", 21);
    public static readonly BackgroundColor Gray_400 = new("bg-gray-400", 22);
    public static readonly BackgroundColor Gray_500 = new("bg-gray-500", 23);
    public static readonly BackgroundColor Gray_600 = new("bg-gray-600", 24);
    public static readonly BackgroundColor Gray_700 = new("bg-gray-700", 25);
    public static readonly BackgroundColor Gray_800 = new("bg-gray-800", 26);
    public static readonly BackgroundColor Gray_900 = new("bg-gray-900", 27);
    public static readonly BackgroundColor Gray_950 = new("bg-gray-950", 28);
    public static readonly BackgroundColor Zinc_50 = new("bg-zinc-50", 29);
    public static readonly BackgroundColor Zinc_100 = new("bg-zinc-100", 30);
    public static readonly BackgroundColor Zinc_200 = new("bg-zinc-200", 31);
    public static readonly BackgroundColor Zinc_300 = new("bg-zinc-300", 32);
    public static readonly BackgroundColor Zinc_400 = new("bg-zinc-400", 33);
    public static readonly BackgroundColor Zinc_500 = new("bg-zinc-500", 34);
    public static readonly BackgroundColor Zinc_600 = new("bg-zinc-600", 35);
    public static readonly BackgroundColor Zinc_700 = new("bg-zinc-700", 36);
    public static readonly BackgroundColor Zinc_800 = new("bg-zinc-800", 37);
    public static readonly BackgroundColor Zinc_900 = new("bg-zinc-900", 38);
    public static readonly BackgroundColor Zinc_950 = new("bg-zinc-950", 39);
    public static readonly BackgroundColor Neutral_50 = new("bg-neutral-50", 40);
    public static readonly BackgroundColor Neutral_100 = new("bg-neutral-100", 41);
    public static readonly BackgroundColor Neutral_200 = new("bg-neutral-200", 42);
    public static readonly BackgroundColor Neutral_300 = new("bg-neutral-300", 43);
    public static readonly BackgroundColor Neutral_400 = new("bg-neutral-400", 44);
    public static readonly BackgroundColor Neutral_500 = new("bg-neutral-500", 45);
    public static readonly BackgroundColor Neutral_600 = new("bg-neutral-600", 46);
    public static readonly BackgroundColor Neutral_700 = new("bg-neutral-700", 47);
    public static readonly BackgroundColor Neutral_800 = new("bg-neutral-800", 48);
    public static readonly BackgroundColor Neutral_900 = new("bg-neutral-900", 49);
    public static readonly BackgroundColor Neutral_950 = new("bg-neutral-950", 50);
    public static readonly BackgroundColor Stone_50 = new("bg-stone-50", 51);
    public static readonly BackgroundColor Stone_100 = new("bg-stone-100", 52);
    public static readonly BackgroundColor Stone_200 = new("bg-stone-200", 53);
    public static readonly BackgroundColor Stone_300 = new("bg-stone-300", 54);
    public static readonly BackgroundColor Stone_400 = new("bg-stone-400", 55);
    public static readonly BackgroundColor Stone_500 = new("bg-stone-500", 56);
    public static readonly BackgroundColor Stone_600 = new("bg-stone-600", 57);
    public static readonly BackgroundColor Stone_700 = new("bg-stone-700", 58);
    public static readonly BackgroundColor Stone_800 = new("bg-stone-800", 59);
    public static readonly BackgroundColor Stone_900 = new("bg-stone-900", 60);
    public static readonly BackgroundColor Stone_950 = new("bg-stone-950", 61);
    public static readonly BackgroundColor Red_50 = new("bg-red-50", 62);
    public static readonly BackgroundColor Red_100 = new("bg-red-100", 63);
    public static readonly BackgroundColor Red_200 = new("bg-red-200", 64);
    public static readonly BackgroundColor Red_300 = new("bg-red-300", 65);
    public static readonly BackgroundColor Red_400 = new("bg-red-400", 66);
    public static readonly BackgroundColor Red_500 = new("bg-red-500", 67);
    public static readonly BackgroundColor Red_600 = new("bg-red-600", 68);
    public static readonly BackgroundColor Red_700 = new("bg-red-700", 69);
    public static readonly BackgroundColor Red_800 = new("bg-red-800", 70);
    public static readonly BackgroundColor Red_900 = new("bg-red-900", 71);
    public static readonly BackgroundColor Red_950 = new("bg-red-950", 72);
    public static readonly BackgroundColor Orange_50 = new("bg-orange-50", 73);
    public static readonly BackgroundColor Orange_100 = new("bg-orange-100", 74);
    public static readonly BackgroundColor Orange_200 = new("bg-orange-200", 75);
    public static readonly BackgroundColor Orange_300 = new("bg-orange-300", 76);
    public static readonly BackgroundColor Orange_400 = new("bg-orange-400", 77);
    public static readonly BackgroundColor Orange_500 = new("bg-orange-500", 78);
    public static readonly BackgroundColor Orange_600 = new("bg-orange-600", 79);
    public static readonly BackgroundColor Orange_700 = new("bg-orange-700", 80);
    public static readonly BackgroundColor Orange_800 = new("bg-orange-800", 81);
    public static readonly BackgroundColor Orange_900 = new("bg-orange-900", 82);
    public static readonly BackgroundColor Orange_950 = new("bg-orange-950", 83);
    public static readonly BackgroundColor Amber_50 = new("bg-amber-50", 84);
    public static readonly BackgroundColor Amber_100 = new("bg-amber-100", 85);
    public static readonly BackgroundColor Amber_200 = new("bg-amber-200", 86);
    public static readonly BackgroundColor Amber_300 = new("bg-amber-300", 87);
    public static readonly BackgroundColor Amber_400 = new("bg-amber-400", 88);
    public static readonly BackgroundColor Amber_500 = new("bg-amber-500", 89);
    public static readonly BackgroundColor Amber_600 = new("bg-amber-600", 90);
    public static readonly BackgroundColor Amber_700 = new("bg-amber-700", 91);
    public static readonly BackgroundColor Amber_800 = new("bg-amber-800", 92);
    public static readonly BackgroundColor Amber_900 = new("bg-amber-900", 93);
    public static readonly BackgroundColor Amber_950 = new("bg-amber-950", 94);
    public static readonly BackgroundColor Yellow_50 = new("bg-yellow-50", 95);
    public static readonly BackgroundColor Yellow_100 = new("bg-yellow-100", 96);
    public static readonly BackgroundColor Yellow_200 = new("bg-yellow-200", 97);
    public static readonly BackgroundColor Yellow_300 = new("bg-yellow-300", 98);
    public static readonly BackgroundColor Yellow_400 = new("bg-yellow-400", 99);
    public static readonly BackgroundColor Yellow_500 = new("bg-yellow-500", 100);
    public static readonly BackgroundColor Yellow_600 = new("bg-yellow-600", 101);
    public static readonly BackgroundColor Yellow_700 = new("bg-yellow-700", 102);
    public static readonly BackgroundColor Yellow_800 = new("bg-yellow-800", 103);
    public static readonly BackgroundColor Yellow_900 = new("bg-yellow-900", 104);
    public static readonly BackgroundColor Yellow_950 = new("bg-yellow-950", 105);
    public static readonly BackgroundColor Lime_50 = new("bg-lime-50", 106);
    public static readonly BackgroundColor Lime_100 = new("bg-lime-100", 107);
    public static readonly BackgroundColor Lime_200 = new("bg-lime-200", 108);
    public static readonly BackgroundColor Lime_300 = new("bg-lime-300", 109);
    public static readonly BackgroundColor Lime_400 = new("bg-lime-400", 110);
    public static readonly BackgroundColor Lime_500 = new("bg-lime-500", 111);
    public static readonly BackgroundColor Lime_600 = new("bg-lime-600", 112);
    public static readonly BackgroundColor Lime_700 = new("bg-lime-700", 113);
    public static readonly BackgroundColor Lime_800 = new("bg-lime-800", 114);
    public static readonly BackgroundColor Lime_900 = new("bg-lime-900", 115);
    public static readonly BackgroundColor Lime_950 = new("bg-lime-950", 116);
    public static readonly BackgroundColor Green_50 = new("bg-green-50", 117);
    public static readonly BackgroundColor Green_100 = new("bg-green-100", 118);
    public static readonly BackgroundColor Green_200 = new("bg-green-200", 119);
    public static readonly BackgroundColor Green_300 = new("bg-green-300", 120);
    public static readonly BackgroundColor Green_400 = new("bg-green-400", 121);
    public static readonly BackgroundColor Green_500 = new("bg-green-500", 122);
    public static readonly BackgroundColor Green_600 = new("bg-green-600", 123);
    public static readonly BackgroundColor Green_700 = new("bg-green-700", 124);
    public static readonly BackgroundColor Green_800 = new("bg-green-800", 125);
    public static readonly BackgroundColor Green_900 = new("bg-green-900", 126);
    public static readonly BackgroundColor Green_950 = new("bg-green-950", 127);
    public static readonly BackgroundColor Blue_50 = new("bg-blue-50", 128);
    public static readonly BackgroundColor Blue_100 = new("bg-blue-100", 129);
    public static readonly BackgroundColor Blue_200 = new("bg-blue-200", 130);
    public static readonly BackgroundColor Blue_300 = new("bg-blue-300", 131);
    public static readonly BackgroundColor Blue_400 = new("bg-blue-400", 132);
    public static readonly BackgroundColor Blue_500 = new("bg-blue-500", 133);
    public static readonly BackgroundColor Blue_600 = new("bg-blue-600", 134);
    public static readonly BackgroundColor Blue_700 = new("bg-blue-700", 135);
    public static readonly BackgroundColor Blue_800 = new("bg-blue-800", 136);
    public static readonly BackgroundColor Blue_900 = new("bg-blue-900", 137);
    public static readonly BackgroundColor Blue_950 = new("bg-blue-950", 138);
    public static readonly BackgroundColor Purple_50 = new("bg-purple-50", 139);
    public static readonly BackgroundColor Purple_100 = new("bg-purple-100", 140);
    public static readonly BackgroundColor Purple_200 = new("bg-purple-200", 141);
    public static readonly BackgroundColor Purple_300 = new("bg-purple-300", 142);
    public static readonly BackgroundColor Purple_400 = new("bg-purple-400", 143);
    public static readonly BackgroundColor Purple_500 = new("bg-purple-500", 144);
    public static readonly BackgroundColor Purple_600 = new("bg-purple-600", 145);
    public static readonly BackgroundColor Purple_700 = new("bg-purple-700", 146);
    public static readonly BackgroundColor Purple_800 = new("bg-purple-800", 147);
    public static readonly BackgroundColor Purple_900 = new("bg-purple-900", 148);
    public static readonly BackgroundColor Purple_950 = new("bg-purple-950", 149);
    public static readonly BackgroundColor Pink_50 = new("bg-pink-50", 150);
    public static readonly BackgroundColor Pink_100 = new("bg-pink-100", 151);
    public static readonly BackgroundColor Pink_200 = new("bg-pink-200", 152);
    public static readonly BackgroundColor Pink_300 = new("bg-pink-300", 153);
    public static readonly BackgroundColor Pink_400 = new("bg-pink-400", 154);
    public static readonly BackgroundColor Pink_500 = new("bg-pink-500", 155);
    public static readonly BackgroundColor Pink_600 = new("bg-pink-600", 156);
    public static readonly BackgroundColor Pink_700 = new("bg-pink-700", 157);
    public static readonly BackgroundColor Pink_800 = new("bg-pink-800", 158);
    public static readonly BackgroundColor Pink_900 = new("bg-pink-900", 159);
    public static readonly BackgroundColor Pink_950 = new("bg-pink-950", 160);

    private BackgroundColor(string name, int value) : base(name, value)
    {
    }
}
