using Ardalis.SmartEnum;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;

namespace Maurosoft.Blazor.Tailwind.Core.Css;

/// <summary>
/// Utilities for controlling the BorderColor of an element.
/// For info, see <see href="https://tailwindcss.com/docs/border-color">border-color</see>
/// </summary>
public sealed class BorderColor : TailwindCssClassBase
{
    public static readonly BorderColor NotSet = new("notset", 1);
    public static readonly BorderColor Inherit = new("border-inherit", 2);
    public static readonly BorderColor Current = new("border-current", 3);
    public static readonly BorderColor Transparent = new("border-transparent", 4);
    public static readonly BorderColor Black = new("border-black", 5);
    public static readonly BorderColor White = new("border-white", 6);
    public static readonly BorderColor Slate_50 = new("border-slate-50", 7);
    public static readonly BorderColor Slate_100 = new("border-slate-100", 8);
    public static readonly BorderColor Slate_200 = new("border-slate-200", 9);
    public static readonly BorderColor Slate_300 = new("border-slate-300", 10);
    public static readonly BorderColor Slate_400 = new("border-slate-400", 11);
    public static readonly BorderColor Slate_500 = new("border-slate-500", 12);
    public static readonly BorderColor Slate_600 = new("border-slate-600", 13);
    public static readonly BorderColor Slate_700 = new("border-slate-700", 14);
    public static readonly BorderColor Slate_800 = new("border-slate-800", 15);
    public static readonly BorderColor Slate_900 = new("border-slate-900", 16);
    public static readonly BorderColor Slate_950 = new("border-slate-950", 17);
    public static readonly BorderColor Gray_50 = new("border-gray-50", 18);
    public static readonly BorderColor Gray_100 = new("border-gray-100", 19);
    public static readonly BorderColor Gray_200 = new("border-gray-200", 20);
    public static readonly BorderColor Gray_300 = new("border-gray-300", 21);
    public static readonly BorderColor Gray_400 = new("border-gray-400", 22);
    public static readonly BorderColor Gray_500 = new("border-gray-500", 23);
    public static readonly BorderColor Gray_600 = new("border-gray-600", 24);
    public static readonly BorderColor Gray_700 = new("border-gray-700", 25);
    public static readonly BorderColor Gray_800 = new("border-gray-800", 26);
    public static readonly BorderColor Gray_900 = new("border-gray-900", 27);
    public static readonly BorderColor Gray_950 = new("border-gray-950", 28);
    public static readonly BorderColor Zinc_50 = new("border-zinc-50", 29);
    public static readonly BorderColor Zinc_100 = new("border-zinc-100", 30);
    public static readonly BorderColor Zinc_200 = new("border-zinc-200", 31);
    public static readonly BorderColor Zinc_300 = new("border-zinc-300", 32);
    public static readonly BorderColor Zinc_400 = new("border-zinc-400", 33);
    public static readonly BorderColor Zinc_500 = new("border-zinc-500", 34);
    public static readonly BorderColor Zinc_600 = new("border-zinc-600", 35);
    public static readonly BorderColor Zinc_700 = new("border-zinc-700", 36);
    public static readonly BorderColor Zinc_800 = new("border-zinc-800", 37);
    public static readonly BorderColor Zinc_900 = new("border-zinc-900", 38);
    public static readonly BorderColor Zinc_950 = new("border-zinc-950", 39);
    public static readonly BorderColor Neutral_50 = new("border-neutral-50", 40);
    public static readonly BorderColor Neutral_100 = new("border-neutral-100", 41);
    public static readonly BorderColor Neutral_200 = new("border-neutral-200", 42);
    public static readonly BorderColor Neutral_300 = new("border-neutral-300", 43);
    public static readonly BorderColor Neutral_400 = new("border-neutral-400", 44);
    public static readonly BorderColor Neutral_500 = new("border-neutral-500", 45);
    public static readonly BorderColor Neutral_600 = new("border-neutral-600", 46);
    public static readonly BorderColor Neutral_700 = new("border-neutral-700", 47);
    public static readonly BorderColor Neutral_800 = new("border-neutral-800", 48);
    public static readonly BorderColor Neutral_900 = new("border-neutral-900", 49);
    public static readonly BorderColor Neutral_950 = new("border-neutral-950", 50);
    public static readonly BorderColor Stone_50 = new("border-stone-50", 51);
    public static readonly BorderColor Stone_100 = new("border-stone-100", 52);
    public static readonly BorderColor Stone_200 = new("border-stone-200", 53);
    public static readonly BorderColor Stone_300 = new("border-stone-300", 54);
    public static readonly BorderColor Stone_400 = new("border-stone-400", 55);
    public static readonly BorderColor Stone_500 = new("border-stone-500", 56);
    public static readonly BorderColor Stone_600 = new("border-stone-600", 57);
    public static readonly BorderColor Stone_700 = new("border-stone-700", 58);
    public static readonly BorderColor Stone_800 = new("border-stone-800", 59);
    public static readonly BorderColor Stone_900 = new("border-stone-900", 60);
    public static readonly BorderColor Stone_950 = new("border-stone-950", 61);
    public static readonly BorderColor Red_50 = new("border-red-50", 62);
    public static readonly BorderColor Red_100 = new("border-red-100", 63);
    public static readonly BorderColor Red_200 = new("border-red-200", 64);
    public static readonly BorderColor Red_300 = new("border-red-300", 65);
    public static readonly BorderColor Red_400 = new("border-red-400", 66);
    public static readonly BorderColor Red_500 = new("border-red-500", 67);
    public static readonly BorderColor Red_600 = new("border-red-600", 68);
    public static readonly BorderColor Red_700 = new("border-red-700", 69);
    public static readonly BorderColor Red_800 = new("border-red-800", 70);
    public static readonly BorderColor Red_900 = new("border-red-900", 71);
    public static readonly BorderColor Red_950 = new("border-red-950", 72);
    public static readonly BorderColor Orange_50 = new("border-orange-50", 73);
    public static readonly BorderColor Orange_100 = new("border-orange-100", 74);
    public static readonly BorderColor Orange_200 = new("border-orange-200", 75);
    public static readonly BorderColor Orange_300 = new("border-orange-300", 76);
    public static readonly BorderColor Orange_400 = new("border-orange-400", 77);
    public static readonly BorderColor Orange_500 = new("border-orange-500", 78);
    public static readonly BorderColor Orange_600 = new("border-orange-600", 79);
    public static readonly BorderColor Orange_700 = new("border-orange-700", 80);
    public static readonly BorderColor Orange_800 = new("border-orange-800", 81);
    public static readonly BorderColor Orange_900 = new("border-orange-900", 82);
    public static readonly BorderColor Orange_950 = new("border-orange-950", 83);
    public static readonly BorderColor Amber_50 = new("border-amber-50", 84);
    public static readonly BorderColor Amber_100 = new("border-amber-100", 85);
    public static readonly BorderColor Amber_200 = new("border-amber-200", 86);
    public static readonly BorderColor Amber_300 = new("border-amber-300", 87);
    public static readonly BorderColor Amber_400 = new("border-amber-400", 88);
    public static readonly BorderColor Amber_500 = new("border-amber-500", 89);
    public static readonly BorderColor Amber_600 = new("border-amber-600", 90);
    public static readonly BorderColor Amber_700 = new("border-amber-700", 91);
    public static readonly BorderColor Amber_800 = new("border-amber-800", 92);
    public static readonly BorderColor Amber_900 = new("border-amber-900", 93);
    public static readonly BorderColor Amber_950 = new("border-amber-950", 94);
    public static readonly BorderColor Yellow_50 = new("border-yellow-50", 95);
    public static readonly BorderColor Yellow_100 = new("border-yellow-100", 96);
    public static readonly BorderColor Yellow_200 = new("border-yellow-200", 97);
    public static readonly BorderColor Yellow_300 = new("border-yellow-300", 98);
    public static readonly BorderColor Yellow_400 = new("border-yellow-400", 99);
    public static readonly BorderColor Yellow_500 = new("border-yellow-500", 100);
    public static readonly BorderColor Yellow_600 = new("border-yellow-600", 101);
    public static readonly BorderColor Yellow_700 = new("border-yellow-700", 102);
    public static readonly BorderColor Yellow_800 = new("border-yellow-800", 103);
    public static readonly BorderColor Yellow_900 = new("border-yellow-900", 104);
    public static readonly BorderColor Yellow_950 = new("border-yellow-950", 105);
    public static readonly BorderColor Lime_50 = new("border-lime-50", 106);
    public static readonly BorderColor Lime_100 = new("border-lime-100", 107);
    public static readonly BorderColor Lime_200 = new("border-lime-200", 108);
    public static readonly BorderColor Lime_300 = new("border-lime-300", 109);
    public static readonly BorderColor Lime_400 = new("border-lime-400", 110);
    public static readonly BorderColor Lime_500 = new("border-lime-500", 111);
    public static readonly BorderColor Lime_600 = new("border-lime-600", 112);
    public static readonly BorderColor Lime_700 = new("border-lime-700", 113);
    public static readonly BorderColor Lime_800 = new("border-lime-800", 114);
    public static readonly BorderColor Lime_900 = new("border-lime-900", 115);
    public static readonly BorderColor Lime_950 = new("border-lime-950", 116);
    public static readonly BorderColor Green_50 = new("border-green-50", 117);
    public static readonly BorderColor Green_100 = new("border-green-100", 118);
    public static readonly BorderColor Green_200 = new("border-green-200", 119);
    public static readonly BorderColor Green_300 = new("border-green-300", 120);
    public static readonly BorderColor Green_400 = new("border-green-400", 121);
    public static readonly BorderColor Green_500 = new("border-green-500", 122);
    public static readonly BorderColor Green_600 = new("border-green-600", 123);
    public static readonly BorderColor Green_700 = new("border-green-700", 124);
    public static readonly BorderColor Green_800 = new("border-green-800", 125);
    public static readonly BorderColor Green_900 = new("border-green-900", 126);
    public static readonly BorderColor Green_950 = new("border-green-950", 127);
    public static readonly BorderColor Blue_50 = new("border-blue-50", 128);
    public static readonly BorderColor Blue_100 = new("border-blue-100", 129);
    public static readonly BorderColor Blue_200 = new("border-blue-200", 130);
    public static readonly BorderColor Blue_300 = new("border-blue-300", 131);
    public static readonly BorderColor Blue_400 = new("border-blue-400", 132);
    public static readonly BorderColor Blue_500 = new("border-blue-500", 133);
    public static readonly BorderColor Blue_600 = new("border-blue-600", 134);
    public static readonly BorderColor Blue_700 = new("border-blue-700", 135);
    public static readonly BorderColor Blue_800 = new("border-blue-800", 136);
    public static readonly BorderColor Blue_900 = new("border-blue-900", 137);
    public static readonly BorderColor Blue_950 = new("border-blue-950", 138);
    public static readonly BorderColor Purple_50 = new("border-purple-50", 139);
    public static readonly BorderColor Purple_100 = new("border-purple-100", 140);
    public static readonly BorderColor Purple_200 = new("border-purple-200", 141);
    public static readonly BorderColor Purple_300 = new("border-purple-300", 142);
    public static readonly BorderColor Purple_400 = new("border-purple-400", 143);
    public static readonly BorderColor Purple_500 = new("border-purple-500", 144);
    public static readonly BorderColor Purple_600 = new("border-purple-600", 145);
    public static readonly BorderColor Purple_700 = new("border-purple-700", 146);
    public static readonly BorderColor Purple_800 = new("border-purple-800", 147);
    public static readonly BorderColor Purple_900 = new("border-purple-900", 148);
    public static readonly BorderColor Purple_950 = new("border-purple-950", 149);
    public static readonly BorderColor Pink_50 = new("border-pink-50", 150);
    public static readonly BorderColor Pink_100 = new("border-pink-100", 151);
    public static readonly BorderColor Pink_200 = new("border-pink-200", 152);
    public static readonly BorderColor Pink_300 = new("border-pink-300", 153);
    public static readonly BorderColor Pink_400 = new("border-pink-400", 154);
    public static readonly BorderColor Pink_500 = new("border-pink-500", 155);
    public static readonly BorderColor Pink_600 = new("border-pink-600", 156);
    public static readonly BorderColor Pink_700 = new("border-pink-700", 157);
    public static readonly BorderColor Pink_800 = new("border-pink-800", 158);
    public static readonly BorderColor Pink_900 = new("border-pink-900", 159);
    public static readonly BorderColor Pink_950 = new("border-pink-950", 160);

    private BorderColor(string name, int value) : base(name, value)
    {
    }
}
