using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace Maurosoft.Blazor.Tailwind.Core.Css;

public sealed class Padding : TailwindCssClassBase
{
    public static readonly Padding NotSet = new("notset", 1);
    public static readonly Padding p_0 = new("p-0", 2);
    public static readonly Padding px_0 = new("px-0", 3);
    public static readonly Padding py_0 = new("py-0", 4);
    public static readonly Padding ps_0 = new("ps-0", 5);
    public static readonly Padding pe_0 = new("pe-0", 6);
    public static readonly Padding pt_0 = new("pt-0", 7);
    public static readonly Padding pr_0 = new("pr-0", 8);
    public static readonly Padding pb_0 = new("pb-0", 9);
    public static readonly Padding pl_0 = new("pl-0", 10);
    public static readonly Padding p_px = new("p-px", 11);
    public static readonly Padding px_px = new("px-px", 12);
    public static readonly Padding py_px = new("py-px", 13);
    public static readonly Padding ps_px = new("ps-px", 14);
    public static readonly Padding pe_px = new("pe-px", 15);
    public static readonly Padding pt_px = new("pt-px", 16);
    public static readonly Padding pr_px = new("pr-px", 17);
    public static readonly Padding pb_px = new("pb-px", 18);
    public static readonly Padding pl_px = new("pl-px", 19);
    public static readonly Padding p_1 = new("p-1", 20);
    public static readonly Padding px_1 = new("px-1", 21);
    public static readonly Padding py_1 = new("py-1", 22);
    public static readonly Padding ps_1 = new("ps-1", 23);
    public static readonly Padding pe_1 = new("pe-1", 24);
    public static readonly Padding pt_1 = new("pt-1", 25);
    public static readonly Padding pr_1 = new("pr-1", 26);
    public static readonly Padding pb_1 = new("pb-1", 27);
    public static readonly Padding pl_1 = new("pl-1", 28);
    public static readonly Padding p_2 = new("p-2", 29);
    public static readonly Padding px_2 = new("px-2", 30);
    public static readonly Padding py_2 = new("py-2", 31);
    public static readonly Padding ps_2 = new("ps-2", 32);
    public static readonly Padding pe_2 = new("pe-2", 33);
    public static readonly Padding pt_2 = new("pt-2", 34);
    public static readonly Padding pr_2 = new("pr-2", 35);
    public static readonly Padding pb_2 = new("pb-2", 36);
    public static readonly Padding pl_2 = new("pl-2", 37);
    public static readonly Padding p_3 = new("p-3", 38);
    public static readonly Padding px_3 = new("px-3", 39);
    public static readonly Padding py_3 = new("py-3", 40);
    public static readonly Padding ps_3 = new("ps-3", 41);
    public static readonly Padding pe_3 = new("pe-3", 42);
    public static readonly Padding pt_3 = new("pt-3", 43);
    public static readonly Padding pr_3 = new("pr-3", 44);
    public static readonly Padding pb_3 = new("pb-3", 45);
    public static readonly Padding pl_3 = new("pl-3", 46);
    public static readonly Padding p_4 = new("p-4", 47);
    public static readonly Padding px_4 = new("px-4", 48);
    public static readonly Padding py_4 = new("py-4", 49);
    public static readonly Padding ps_4 = new("ps-4", 50);
    public static readonly Padding pe_4 = new("pe-4", 51);
    public static readonly Padding pt_4 = new("pt-4", 52);
    public static readonly Padding pr_4 = new("pr-4", 53);
    public static readonly Padding pb_4 = new("pb-4", 54);
    public static readonly Padding pl_4 = new("pl-4", 55);
    public static readonly Padding p_5 = new("p-5", 56);
    public static readonly Padding px_5 = new("px-5", 57);
    public static readonly Padding py_5 = new("py-5", 58);
    public static readonly Padding ps_5 = new("ps-5", 59);
    public static readonly Padding pe_5 = new("pe-5", 60);
    public static readonly Padding pt_5 = new("pt-5", 61);
    public static readonly Padding pr_5 = new("pr-5", 62);
    public static readonly Padding pb_5 = new("pb-5", 63);
    public static readonly Padding pl_5 = new("pl-5", 64);
    public static readonly Padding p_6 = new("p-6", 65);
    public static readonly Padding px_6 = new("px-6", 66);
    public static readonly Padding py_6 = new("py-6", 67);
    public static readonly Padding ps_6 = new("ps-6", 68);
    public static readonly Padding pe_6 = new("pe-6", 69);
    public static readonly Padding pt_6 = new("pt-6", 70);
    public static readonly Padding pr_6 = new("pr-6", 71);
    public static readonly Padding pb_6 = new("pb-6", 72);
    public static readonly Padding pl_6 = new("pl-6", 73);
    public static readonly Padding p_7 = new("p-7", 74);
    public static readonly Padding px_7 = new("px-7", 75);
    public static readonly Padding py_7 = new("py-7", 76);
    public static readonly Padding ps_7 = new("ps-7", 77);
    public static readonly Padding pe_7 = new("pe-7", 78);
    public static readonly Padding pt_7 = new("pt-7", 79);
    public static readonly Padding pr_7 = new("pr-7", 80);
    public static readonly Padding pb_7 = new("pb-7", 81);
    public static readonly Padding pl_7 = new("pl-7", 82);
    public static readonly Padding p_8 = new("p-8", 83);
    public static readonly Padding px_8 = new("px-8", 84);
    public static readonly Padding py_8 = new("py-8", 85);
    public static readonly Padding ps_8 = new("ps-8", 86);
    public static readonly Padding pe_8 = new("pe-8", 87);
    public static readonly Padding pt_8 = new("pt-8", 88);
    public static readonly Padding pr_8 = new("pr-8", 89);
    public static readonly Padding pb_8 = new("pb-8", 90);
    public static readonly Padding pl_8 = new("pl-8", 91);
    public static readonly Padding p_9 = new("p-9", 92);
    public static readonly Padding px_9 = new("px-9", 93);
    public static readonly Padding py_9 = new("py-9", 94);
    public static readonly Padding ps_9 = new("ps-9", 95);
    public static readonly Padding pe_9 = new("pe-9", 96);
    public static readonly Padding pt_9 = new("pt-9", 97);
    public static readonly Padding pr_9 = new("pr-9", 98);
    public static readonly Padding pb_9 = new("pb-9", 99);
    public static readonly Padding pl_9 = new("pl-9", 100);
    public static readonly Padding p_10 = new("p-10", 101);
    public static readonly Padding px_10 = new("px-10", 102);
    public static readonly Padding py_10 = new("py-10", 103);
    public static readonly Padding ps_10 = new("ps-10", 104);
    public static readonly Padding pe_10 = new("pe-10", 105);
    public static readonly Padding pt_10 = new("pt-10", 106);
    public static readonly Padding pr_10 = new("pr-10", 107);
    public static readonly Padding pb_10 = new("pb-10", 108);
    public static readonly Padding pl_10 = new("pl-10", 109);

    private Padding(string name, int value) : base(name, value) { }
}
