using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Ardalis.SmartEnum;

namespace Maurosoft.Blazor.Tailwind.Core.Css.Properties.Sizing;

public class ButtonSize : TailwindCssClassBase
{
    public static readonly ButtonSize NotSet = new("notset", 0);
    public static readonly ButtonSize Size_0 = new("size-0", 1);
    public static readonly ButtonSize Size_1 = new("size-1", 2);
    public static readonly ButtonSize Size_2 = new("size-2", 3);
    public static readonly ButtonSize Size_3 = new("size-3", 4);
    public static readonly ButtonSize Size_4 = new("size-4", 5);
    public static readonly ButtonSize Size_5 = new("size-5", 6);
    public static readonly ButtonSize Size_6 = new("size-6", 7);
    public static readonly ButtonSize Size_7 = new("size-7", 8);
    public static readonly ButtonSize Size_8 = new("size-8", 9);
    public static readonly ButtonSize Size_9 = new("size-9", 10);
    public static readonly ButtonSize Size_10 = new("size-10", 11);
    public static readonly ButtonSize Size_11 = new("size-11", 12);
    public static readonly ButtonSize Size_12 = new("size-12", 13);
    public static readonly ButtonSize Size_14 = new("size-14", 14);
    public static readonly ButtonSize Size_16 = new("size-16", 15);
    public static readonly ButtonSize Size_20 = new("size-20", 16);
    public static readonly ButtonSize Size_24 = new("size-24", 17);
    public static readonly ButtonSize Size_28 = new("size-28", 18);
    public static readonly ButtonSize Size_32 = new("size-32", 19);
    public static readonly ButtonSize Size_36 = new("size-36", 20);
    public static readonly ButtonSize Size_40 = new("size-40", 21);
    public static readonly ButtonSize Size_44 = new("size-44", 22);
    public static readonly ButtonSize Size_48 = new("size-48", 23);
    public static readonly ButtonSize Size_52 = new("size-52", 24);
    public static readonly ButtonSize Size_56 = new("size-56", 25);
    public static readonly ButtonSize Size_60 = new("size-60", 26);
    public static readonly ButtonSize Size_64 = new("size-64", 27);
    public static readonly ButtonSize Size_72 = new("size-72", 28);
    public static readonly ButtonSize Size_80 = new("size-80", 29);
    public static readonly ButtonSize Size_96 = new("size-96", 30);
    public static readonly ButtonSize Size_Auto = new("size-auto", 31);
    public static readonly ButtonSize Size_Px = new("size-px", 32);
    public static readonly ButtonSize Size_1_2 = new("size-1/2", 33);
    public static readonly ButtonSize Size_1_3 = new("size-1/3", 34);
    public static readonly ButtonSize Size_2_3 = new("size-2/3", 35);
    public static readonly ButtonSize Size_1_4 = new("size-1/4", 36);
    public static readonly ButtonSize Size_2_4 = new("size-2/4", 37);
    public static readonly ButtonSize Size_3_4 = new("size-3/4", 38);
    public static readonly ButtonSize Size_1_5 = new("size-1/5", 39);
    public static readonly ButtonSize Size_2_5 = new("size-2/5", 40);
    public static readonly ButtonSize Size_3_5 = new("size-3/5", 41);
    public static readonly ButtonSize Size_4_5 = new("size-4/5", 42);
    public static readonly ButtonSize Size_1_6 = new("size-1/6", 43);
    public static readonly ButtonSize Size_2_6 = new("size-2/6", 44);
    public static readonly ButtonSize Size_3_6 = new("size-3/6", 45);
    public static readonly ButtonSize Size_4_6 = new("size-4/6", 46);
    public static readonly ButtonSize Size_5_6 = new("size-5/6", 47);
    public static readonly ButtonSize Size_1_12 = new("size-1/12", 48);
    public static readonly ButtonSize Size_2_12 = new("size-2/12", 49);
    public static readonly ButtonSize Size_3_12 = new("size-3/12", 50);
    public static readonly ButtonSize Size_4_12 = new("size-4/12", 51);
    public static readonly ButtonSize Size_5_12 = new("size-5/12", 52);
    public static readonly ButtonSize Size_6_12 = new("size-6/12", 53);
    public static readonly ButtonSize Size_7_12 = new("size-7/12", 54);
    public static readonly ButtonSize Size_8_12 = new("size-8/12", 55);
    public static readonly ButtonSize Size_9_12 = new("size-9/12", 56);
    public static readonly ButtonSize Size_10_12 = new("size-10/12", 57);
    public static readonly ButtonSize Size_11_12 = new("size-11/12", 58);
    public static readonly ButtonSize Size_Full = new("size-full", 59);
    public static readonly ButtonSize Size_Fit = new("size-fit", 60);
    public static readonly ButtonSize Size_Min = new("size-min", 61);
    public static readonly ButtonSize Size_Max = new("size-max", 62);
    public static readonly ButtonSize Size_0v5 = new("size-0.5", 63);
    public static readonly ButtonSize Size_1v5 = new("size-1.5", 64);
    public static readonly ButtonSize Size_2v5 = new("size-2.5", 65);
    public static readonly ButtonSize Size_3v5 = new("size-3.5", 66);
    public static readonly ButtonSize ExtraSmall = new("px-3 py-2 text-xs", 100);
    public static readonly ButtonSize Small = new("px-3 py-2 text-sm", 101);
    public static readonly ButtonSize Base = new("px-5 py-2.5 text-sm", 102);
    public static readonly ButtonSize Large = new("px-5 py-3 text-base", 103);
    public static readonly ButtonSize ExtraLarge = new("px-6 py-3.5 text-base", 104);

    private ButtonSize(string name, int value) : base(name, value) { }
}
